cuda_visible_devices: "0,1"
exp_name: "libero_10"
data_dir: "data/preprocessed/libero_10"
model: "CVAE-B"
results_dir: "cvae_results/libero_10"
flow_horizon: 16
obs_history: 16
img_patch_size: 8
img_size: [128, 128]
lr: 2e-5
calculate_scale_and_direction: true
data_aug: false
aux: true
flow_normalize: false
min_point_num: 100
max_point_num: 529
track_point_num: 529
epochs: 50000
global_seed: 666
num_workers: 16
log_every: 100
ckpt_every: 2000
eval: true
load_ckpt: false
wandb: true
global_batch_size: 128
eye_in_hand: false
weight_loss: true
weight: 100