cuda_visible_devices: "1,2,3,4"
exp_name: "libero_10"
data_dir: "data/preprocessed/libero_10"
results_dir: "dynamics_results/libero_10"
model: "DynamicsModel-B"
flow_aug: true
flow_horizon: 16
obs_history: 4
img_size: [128, 128]
flow_normalize: false
lr: 1e-4
vae_encode: true
min_track_pt: 100
max_track_pt: 529
epochs: 50000
vae: "ema"
global_batch_size: 16
global_seed: 3407
num_workers: 16
log_every: 100
ckpt_every: 2000
eval: true
eval_diffusion_step: 300
learn_sigma: true
load_ckpt: false
ckpt_path: None
wandb: false
eye_in_hand: false
